heat_template_version: 2014-10-16

description: >
  Fleet instances for stateless workers

resources:

  stateless_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: True
      shared: False

  stateless_subnet:
    type: OS::Neutron::Subnet
    depends_on: [ stateless_network ]
    properties:
      cidr: {get_param: stateless_subnet_cidr}
      network: {get_resource: stateless_network}
      allocation_pools: [{"start" : {get_param: stateless_subnet_start}, "end" : {get_param: stateless_subnet_end}}]
      dns_nameservers: {get_param: dns_nameservers}
      enable_dhcp: True
      gateway_ip: {get_param: stateless_gateway_ip}
      ip_version: 4
      host_routes:
        - destination: "0.0.0.0/0"
          nexthop: {get_param: stateless_gateway_ip}

  stateless_interface:
    type: OS::Neutron::RouterInterface
    depends_on: [ stateless_subnet ]
    properties:
      router_id: { get_param: router }
      subnet_id: { get_resource: stateless_subnet }

  securitygroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 2379
          port_range_max: 2380
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 5000
          port_range_max: 5000
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 179
          port_range_max: 179
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 8472
          port_range_max: 8472
          direction: ingress
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
          direction: ingress

  stateless_anti:
    type: OS::Nova::ServerGroup
    properties:
      name: "stateless"
      policies: ["anti-affinity"] # Beware about the number of compute nodes

  stateless_group:
    depends_on: [ stateless_interface, securitygroup, stateless_anti ]
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 0
      desired_capacity: { get_param: size }
      max_size: 20
      resource:
        type: "StatelessInstance"
        properties:
          floatingip_network_name: { get_param: floatingip_network_name }
          anti_affinity: { get_resource: stateless_anti }
          key_name: { get_param: key_name }
          security_group: { get_resource: securitygroup }
          network: { get_resource: stateless_network }
          subnet: { get_resource: stateless_subnet }
          instance_basename: "stateless"
          flavor: { get_param: flavor }
          image: { get_param: image }
          etcd_initial_cluster: { get_param: etcd_initial_cluster }
          fleet_state: "stateless"

  scale_up:
    depends_on: [ stateless_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: stateless_group}
      cooldown: 60
      scaling_adjustment: 1

  scale_down:
    depends_on: [ stateless_group ]
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: stateless_group}
      cooldown: 60
      scaling_adjustment: -1

parameters:
  key_name:
    type: string
    label: Name of keypair to assign to servers
    description: key_name=foo
    constraints:
      - custom_constraint: nova.keypair

  stateless_subnet_cidr:
    type: string
    default: "192.168.2.0/24"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}/[0-9]{1,2}"
        description: Must be a CIDR like 192.168.1.0/24

  stateless_subnet_start:
    type: string
    default: "192.168.2.100"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  stateless_subnet_end:
    type: string
    default: "192.168.2.200"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  stateless_gateway_ip:
    type: string
    default: "192.168.2.254"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  stateless_gateway_ip:
    type: string
    default: "192.168.2.254"
    constraints:
      - allowed_pattern: "[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}"
        description: Must be a valid IP address like 192.168.1.200

  dns_nameservers:
    type: comma_delimited_list
    label: DNS nameservers
    description: dns_nameservers=8.8.8.8,8.8.4.4

  flavor:
    type: string
    label: The flavor for Instances
    description: flavor=m1.medium
    constraints:
      - custom_constraint: nova.flavor

  image:
    type: string
    label: The debian image based for Instances
    description: image=debian-8-2016-01-01
    constraints:
      - custom_constraint: glance.image

  router:
    type: string
    description: Router id where connect interface to subnet

  etcd_initial_cluster:
    type: string
    description: "static0=http://192.168.1.10:2380,static1=http://192.168.1.11:2380,static2=http://192.168.1.12:2380"

  size:
    type: number
    default: 2

  floatingip_network_name:
    type: string
    label: The Floating IP network for NAT
    description: floatingip_network_name=public


outputs:
  scale_up:
    value:
      - {get_attr: [scale_up, alarm_url]}

  scale_down:
    value:
      - {get_attr: [scale_down, alarm_url]}